services:
  node1:
    build: .
    container_name: exkv_node1
    environment:
      - PORT=4000
      - NODE_NAME=node1@exkv
      - COOKIE=secret
    ports:
      - "4000:4000"

  node2:
    build: .
    container_name: exkv_node2
    environment:
      - PORT=4001
      - NODE_NAME=node2@exkv
      - COOKIE=secret
    ports:
      - "4001:4000"

  node3:
    build: .
    container_name: exkv_node3
    environment:
      - PORT=4002
      - NODE_NAME=node3@exkv
      - COOKIE=secret
    ports:
      - "4002:4000"
